theme: jekyll-theme-slate
title: Convo's with Rachael
description: I have had a lot of conversations with code school grads/career switchers since I made the career
switch from teaching into software engineering and thought it was about time to start collecting all those tips/
resources etc.
